In [6]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
import os, sys
from pathlib import Path
# Add the 'modules' folder to the import path
import openai
sys.path.append(os.path.join('..', 'modules'))
import pandas as pd
pd.set_option('display.max_columns', 9000)
import utils
import gptutils
cf = utils.load_yaml_file(os.path.join('..', 'config', 'key.yaml'))
openaiclient = openai.OpenAI(
  api_key=cf['openaipivot'],  # this is also the default, it can be omitted
)
lpath=Path('../data')
#df = pd.read_excel(lpath/'sample_200_quality 2.xlsx')
df=pd.read_excel(lpath/'sample_200_quality_ass.xlsx')
df=df.iloc[:,:3]
#read only first 10 rows of the dataframe


df

,key,2018_description,2023_description
0,embrace-io,Embrace.io is a group of Los Angeles-based dat...,Embrace empowers engineers to manage the compl...
1,joget-inc-,"Joget, Inc. is the developer and manager of th...","Joget, Inc is the developer of the Joget open ..."
2,zeto-3,Zeto is a medical technology startup transform...,Zeto is a commercial stage medical technology ...
3,baebies,Baebies is guided by a vision that every newbo...,Baebies was founded in 2014 by Richard West an...
4,sifive,SiFive Coreplex IP are the most widely deploye...,SiFive designs chips for the semiconductor ind...
...,...,...,...
195,derivative-path-inc,Who We Are: Derivative Path is a San Francisco...,Derivative Path provides a technology-led solu...
196,inpher-io,"Inpher is a veteran team of entrepreneurs, cry...",Inpher.io is a secret computing technology fo...
197,pyze,Pyze lets brands and enterprises maximize user...,Pyze helps enterprises continuously improve bu...
198,green-bits,Industry Overview: \nThe legal cannabis indust...,"Greenbits empowers more than 1,200 cannabis re..."
199,exabeam,Exabeam is a big data security analytics compa...,Exabeam is a global cybersecurity leader that ...

In [8]:
#This proepares a record of the prompt, adding it to a dataframe. 
#The idea is that you can then review the dataframe to make sure everythigg looks good. 
substitute = ['key','2018_description','2023_description']
prompt_file = '../prompts/pivot-v3-api-3'
model = "o4-mini-2025-04-16"
df=gptutils.prepare_prompt_dataframe(df, prompt_file, substitute,  model, print_prompt=False)

#run it on the whole dataframe
df

,key,2018_description,2023_description,template,prompt,model
0,embrace-io,Embrace.io is a group of Los Angeles-based dat...,Embrace empowers engineers to manage the compl...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
1,joget-inc-,"Joget, Inc. is the developer and manager of th...","Joget, Inc is the developer of the Joget open ...",../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
2,zeto-3,Zeto is a medical technology startup transform...,Zeto is a commercial stage medical technology ...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
3,baebies,Baebies is guided by a vision that every newbo...,Baebies was founded in 2014 by Richard West an...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
4,sifive,SiFive Coreplex IP are the most widely deploye...,SiFive designs chips for the semiconductor ind...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
...,...,...,...,...,...,...
195,derivative-path-inc,Who We Are: Derivative Path is a San Francisco...,Derivative Path provides a technology-led solu...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
196,inpher-io,"Inpher is a veteran team of entrepreneurs, cry...",Inpher.io is a secret computing technology fo...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
197,pyze,Pyze lets brands and enterprises maximize user...,Pyze helps enterprises continuously improve bu...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
198,green-bits,Industry Overview: \nThe legal cannabis indust...,"Greenbits empowers more than 1,200 cannabis re...",../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16
199,exabeam,Exabeam is a big data security analytics compa...,Exabeam is a global cybersecurity leader that ...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,o4-mini-2025-04-16

In [9]:
print(df['prompt'][0])

Evaluate the business descriptions:

key: embrace-io
2018_description: Embrace.io is a group of Los Angeles-based data junkies who have built top-grossing apps. They are supported by mobile-focused investors, including leaders from Parse, Burstly / Testflight, MoPub, and Scopely, who are familiar with the pain of building, releasing, and running large-scale mobile apps. Since its founding less than a year ago, Embrace.io has already grown to support trillions of mobile events from many of the world’s most popular apps.
2023_description: Embrace empowers engineers to manage the complexity of mobile to build better, bolder experiences. At a time when mobile is more crucial than ever, teams often face fragmented solutions, missing data, and an inability to surface issues. With Embrace, engineers can identify and prioritize the impact of any issues with detailed behavioral and technical context to resolve them instantly. By eliminating guesswork, Embrace illuminates opportunities to perfect performance and build the best mobile experiences possible.

**part1: Pivot Assessment**\n\n*Context:* In this evaluation, a 'pivot' is defined as fundamentally changing the direction of a business when you realize the current products or services aren't meeting the needs of the market.\n\n*Instructions:* For each row in the dataset, carefully review the text descriptions of the companies in 2018 and 2023. Using the provided definition, assess whether a pivot has occurred. Assign a '1' in the pivot column if a pivot has occurred; otherwise, enter '0.' Additionally, indicate the probability of a pivot occurrence (0-100). Explain the factors influencing your decision regarding the pivot assessment in the justification column.\n\n

**part2: Pivot Type Assessments**\n\n*Context:* Common pivot types represent systematic changes in business models. Consider the following types of pivots:\n1. 'Zoom-in pivot': A single feature becomes the whole product.\n2. 'Zoom-out pivot': The whole product becomes a single feature of a larger product.\n3. 'Customer segment pivot': Targeting the correct customer for whom the product was built.\n4. 'Customer needs pivot': The problem being solved is unimportant to the customer; consider changing it.\n5. 'Platform pivot': Changing from an application to a platform or vice versa.\n6. 'Business architecture pivot': Changing the business architecture (e.g., from high volume, low margin to high margin, low volume).\n7. 'Value capture pivot': Changing the way value is captured.\n8. 'Engine of growth pivot': Changing the growth strategy for more profitable growth.\n9. 'Channel pivot': A channel pivot is a recognition that the same basic solution could be delivered through a different channel with greater effectiveness.\n10. 'Technology pivot': Keeping everything the same but adopting new technology (e.g., cloud computing).\n\n*Instructions:* For each row in the dataset, if you believe a pivot has occurred (i.e., you have entered a '1' in the pivot column for Part 1), use the provided definitions of pivot types to indicate the pivot types (can be more than one) in the associated labeled columns. Assign a '1' if that pivot type has occurred; otherwise, enter '0.' You must enter at least 1 pivot type if you indicated that a pivot occurred.

**part3: Example of business descriptions that do not pivot "0" and pivot "1"
  "examples_ pivot ": {
"0": " Business_description_2018: Take1 Marketing, Inc. is a full service marketing firm focused on getting your business in front of customers. We can provide everything from website design, professional video services, SEM, and SEO. Our company is at the forefront of video production and optimization with mobile applications utilizing google hangouts to increase customer exposure and interaction! Using the latest software, my team is constantly staying ahead of the competition. We are showing clients all over the country how to generate leads, dominate on social media sites, and how to increase their ROI through simple online research, analysis, optimization, and content management! Imagine having your videos spread out on the top video sites, the top audio sites, and the 50+ social media sites available to you. We can help your business explode overnight! Call us today for a FREE quote and complimentary website Audit! Business_description_2023: Take1 Marketing is a marketing firm on getting your business in front of customers. They can provide everything from website design, professional video services, SEM, and SEO. Our company is at the forefront of video production and optimization with mobile applications utilizing google hangouts to increase customer exposure and interaction! Using the latest software, my team is constantly staying ahead of the competition. We are showing clients all over the country how to generate leads, dominate on social media sites, and how to increase their ROI through simple online research, analysis, optimization, and content management. Imagine having your videos spread out on the top video sites.",
"1": "Business_description_2018: With nearly 20 years of experience and hundreds of happy clients, Information Technology Professionals provides managed IT service and strategy for small to mid-sized businesses, delivering customized technology solutions that allow their clients to function at peak performance and profitability. While they serve clients of all shapes and sizes across a variety of industries, they are highly experienced in meeting IT needs in the manufacturing, medical, and professional services (both legal and financial) sectors. Business_description_2023: If you are looking for travel tips, health guides, and many more tips or tricks, visit the weblyen and read our blogs. And solve your problems or issues by yourself. "
}

Sample JSON return:
{'key': key
'pivot': 0,
'probability_pivot': 0,
'justification': "justification",
'zoom-in_pivot': 0,
'zoom-out_pivot': 0,
'customer_segment_pivot': 0,
'customer_needs_pivot': 0,
'platform_pivot': 0,
'business_architecture_pivot': 0,
'value_capture_pivot': 0,
'engine_of_growth_pivot': 0,
'channel pivot': 0,
'technology_pivot': 0}

In [10]:
#This run all startups in the dataframe.
dftemp, response, responseall=gptutils.run_df_openai(openaiclient,df[0:2], save=True)
responseall

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [9]:
dftemp

,key,2018_description,2023_description,template,prompt,model,response,file
0,embrace-io,Embrace.io is a group of Los Angeles-based dat...,Embrace empowers engineers to manage the compl...,../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,gpt-4-1106-preview,"{\n ""key"": ""embrace-io"",\n ""pivot"": 0,\n ""p...",../responses/2024-02-22_11-50-59.txt
1,joget-inc-,"Joget, Inc. is the developer and manager of th...","Joget, Inc is the developer of the Joget open ...",../prompts/pivot-v3-api-3,\nEvaluate the business descriptions:\n\nkey: ...,gpt-4-1106-preview,"{\n ""key"": ""joget-inc-"",\n ""pivot"": 0,\n ""p...",../responses/2024-02-22_11-51-11.txt

In [11]:
#This runs all of the dataframe. 
dfnew, response, responseall=gptutils.run_df_openai(openaiclient,df, save=True)
# save df new to a pickle file
dfnew.to_pickle(lpath/'dfnew.pkl')

In [ ]:
example={'key': 'key',
'pivot': 0,
'probability_pivot': 0,
'justification': "justification",
'zoom-in_pivot': 0,
'zoom-out_pivot': 0,
'customer_segment_pivot': 0,
'customer_needs_pivot': 0,
'platform_pivot': 0,
'business_architecture_pivot': 0,
'value_capture_pivot': 0,
'engine_of_growth_pivot': 0,
'channel pivot': 0,
'technology_pivot': 0}

dfnew2 = dfnew.apply(gptutils.process_json, ex=example, axis=1)

In [ ]:
# save dfnew2 to a csv file
dfnew2.to_pickle('../data/sample_200_pivot.pkl')
dfnew2.to_csv('../data/sample_200_pivot.csv', index=False)
dfnew2.to_excel('../data/sample_200_pivot.xlsx', engine='xlsxwriter')